<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/16 22:09:14

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=testcrud',
  'username' => 'root',
  'password' => 'seawolf',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
