<?php


/**
 * Skeleton subclass for performing query and update operations on the 'test_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 16 22:19:19 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TestProductPeer extends BaseTestProductPeer {

} // TestProductPeer
