<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/05/16 22:42:39
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sftesterpropel' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfwebdebugpanelpropel' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'sfpropelmanytomany' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropelpager' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropeldata' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfpropelbehavior' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropel' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropeldatabaseschema' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfmixer' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropelgeneratemoduletask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelbuildformstask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropelconfiguredatabasetask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfpropelschematoymltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropelbuildalltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfphinglistener' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfphing' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfpropelbasetask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelbuildallloadtask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbuildsqltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelbuildtask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropeldataloadtask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelbuildschematask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropeldatadumptask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropelgraphviztask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelbuildfilterstask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelgenerateadmintask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelschematoxmltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelinsertsqltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelbuildmodeltask' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfwidgetformpropelchoice' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfpropeldatabase' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'swift_propelspool' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfformfilterpropel' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelformgenerator' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',
  'sfpropelformfiltergenerator' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelbehaviorsymfonybehaviors' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviori18n' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviorbase' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviori18ntranslation' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviortimestampable' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropelbehaviorsymfony' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfvalidatorpropelchoice' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfpropelroute' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfpropellogger' => '/home/sfprojects/test/lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',

  // project
  'basetestcatalogform' => '/home/sfprojects/test/lib/form/base/BaseTestCatalogForm.class.php',
  'basetestproductform' => '/home/sfprojects/test/lib/form/base/BaseTestProductForm.class.php',
  'testcatalogform' => '/home/sfprojects/test/lib/form/TestCatalogForm.class.php',
  'baseformpropel' => '/home/sfprojects/test/lib/form/BaseFormPropel.class.php',
  'testproductform' => '/home/sfprojects/test/lib/form/TestProductForm.class.php',
  'baseform' => '/home/sfprojects/test/lib/form/BaseForm.class.php',
  'basetestcatalogformfilter' => '/home/sfprojects/test/lib/filter/base/BaseTestCatalogFormFilter.class.php',
  'basetestproductformfilter' => '/home/sfprojects/test/lib/filter/base/BaseTestProductFormFilter.class.php',
  'testproductformfilter' => '/home/sfprojects/test/lib/filter/TestProductFormFilter.class.php',
  'testcatalogformfilter' => '/home/sfprojects/test/lib/filter/TestCatalogFormFilter.class.php',
  'baseformfilterpropel' => '/home/sfprojects/test/lib/filter/BaseFormFilterPropel.class.php',

  // project_model
  'testproduct' => '/home/sfprojects/test/lib/model/TestProduct.php',
  'basetestproductpeer' => '/home/sfprojects/test/lib/model/om/BaseTestProductPeer.php',
  'basetestcatalog' => '/home/sfprojects/test/lib/model/om/BaseTestCatalog.php',
  'basetestproduct' => '/home/sfprojects/test/lib/model/om/BaseTestProduct.php',
  'basetestcatalogpeer' => '/home/sfprojects/test/lib/model/om/BaseTestCatalogPeer.php',
  'testcatalogtablemap' => '/home/sfprojects/test/lib/model/map/TestCatalogTableMap.php',
  'testproducttablemap' => '/home/sfprojects/test/lib/model/map/TestProductTableMap.php',
  'testcatalogpeer' => '/home/sfprojects/test/lib/model/TestCatalogPeer.php',
  'testproductpeer' => '/home/sfprojects/test/lib/model/TestProductPeer.php',
  'testcatalog' => '/home/sfprojects/test/lib/model/TestCatalog.php',

  // application
  'myuser' => '/home/sfprojects/test/apps/backend/lib/myUser.class.php',

  // modules
);
